export const FETCH_COUNTRYLIST_REQUEST = "FETCH_COUNTRYLIST_REQUEST"
export const FETCH_COUNTRYLIST_SUCCESS = "FETCH_COUNTRYLIST_SUCCESS"
export const FETCH_COUNTRYLIST_FAIL = "FETCH_COUNTRYLIST_FAIL"
